# All available hooks: https://pre-commit.com/hooks.html
# R specific hooks: https://github.com/lorenzwalthert/precommit
default_install_hook_types: [pre-commit, pre-push]

repos:
-   repo: https://github.com/lorenzwalthert/precommit
    rev: v0.4.3.9026
    hooks:
    -   id: roxygenize
        additional_dependencies:
        -   crul
        -   dplyr
        -   glue
        -   haven
        -   magrittr
        -   openNLP
        -   purrr
        -   qualtRics
        -   rlang
        -   sjlabelled
        -   slowraker
        -   SnowballC
        -   stringi
        -   stringr
        -   tibble
        -   tidyr
        -   xml2
        -   vctrs
    -   id: use-tidy-description
    -   id: spell-check
        files: '^(DESCRIPTION|README\.md|README\.Rmd|man/|vignettes/)'
        exclude: >
          (?x)^(
          .*\.[rR]|
          .*\.feather|
          .*\.jpeg|
          .*\.pdf|
          .*\.png|
          .*\.py|
          .*\.RData|
          .*\.rds|
          .*\.Rds|
          .*\.Rproj|
          .*\.sh|
          (.*/|)\.gitignore|
          (.*/|)\.gitlab-ci\.yml|
          (.*/|)\.lintr|
          (.*/|)\.pre-commit-.*|
          (.*/|)\.Rbuildignore|
          (.*/|)\.Renviron|
          (.*/|)\.Rprofile|
          (.*/|)\.travis\.yml|
          (.*/|)appveyor\.yml|
          (.*/|)NAMESPACE|
          (.*/|)renv/settings\.dcf|
          (.*/|)renv\.lock|
          (.*/|)WORDLIST|
          \.github/workflows/.*|
          data/.*|
          tests/.*|
          )$
    -   id: lintr
        files: '^(R|tests)/.*\.[rR]$'
    -   id: readme-rmd-rendered
    -   id: parsable-R
        files: '^(R|tests)/.*\.[rR]$|^README\.Rmd$|^vignettes/.*\.[Rr]md$'
    -   id: no-browser-statement
        files: '^(R|tests)/.*\.[rR]$'
    -   id: no-debug-statement
        files: '^(R|tests)/.*\.[rR]$'
    -   id: deps-in-desc
        files: '^(R|tests)/.*\.[rR]$|^README\.Rmd$|^vignettes/.*\.[Rr]md$'
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks: 
    -   id: check-added-large-files
        args: ['--maxkb=200']
    -   id: file-contents-sorter
        files: '^\.Rbuildignore$'
    -   id: end-of-file-fixer
        exclude: '\.Rd|tests/.*'
-   repo: https://github.com/pre-commit-ci/pre-commit-ci-config
    rev: v1.6.1
    hooks:
    # Only required when https://pre-commit.ci is used for config validation
    -   id: check-pre-commit-ci-config
-   repo: local
    hooks:
    -   id: forbid-to-commit
        name: Don't commit common R artifacts
        entry: Cannot commit .Rhistory, .RData, .Rds or .rds.
        language: fail
        files: '\.(Rhistory|RData|Rds|rds)$'
        # `exclude: <regex>` to allow committing specific files
    -   id: testthat
        name: Run testthat suite
        entry: Rscript -e 'devtools::test()'
        language: system
        pass_filenames: false
        stages: [pre-commit]
    -   id: pkgcheck
        name: Run rOpenSci pkgcheck audit
        entry: Rscript -e 'checks <- pkgcheck::pkgcheck(); print(checks); summary <- pkgcheck:::summarise_all_checks(checks); quit(save = "no", status = if (isTRUE(attr(summary, "checks_okay"))) 0 else 1)'
        language: system
        pass_filenames: false
        stages: [pre-commit]
    -   id: r-cmd-check-no-manual
        name: Run R CMD check without manual
        entry: Rscript -e 'devtools::check(args = "--no-manual")'
        language: system
        pass_filenames: false
        stages: [pre-commit]
    -   id: r-cmd-check
        name: Run R CMD check
        entry: Rscript -e 'devtools::check()'
        language: system
        pass_filenames: false
        stages: [pre-push]

ci:
    autoupdate_schedule: monthly
