#' Create Labelled Survey Data
#'
#' Download Qualtrics responses through \code{qualtRics} and apply a Variable
#' Dictionary generated by \code{\link[qualtdict]{dict_generate}}. Export
#' Variables are matched by \code{response_column_id}, renamed to
#' \code{variable_name}, and labelled with question, item, level, and label
#' metadata using \code{sjlabelled}.
#'
#' @inheritParams dict_validate
#' @param extra_columns A character vector of raw response columns to retain in
#' the Labelled Survey Data in addition to Export Variables. Defaults to
#' \code{c("externalDataReference", "startDate", "endDate")}. Missing
#' user-specified columns error; missing default columns warn and are skipped.
#' Use \code{NULL} to retain no extra columns.
#' @param exclude_findings Which findings to exclude after survey download.
#' \code{"none"} keeps all downloaded variables represented in the Variable
#' Dictionary. \code{"validation"} excludes rows with Validation Findings.
#' @param ... Other arguments passed to
#' \code{\link[qualtRics]{fetch_survey}}. Filtering arguments such as
#' \code{include_questions} may be passed through. qualtdict owns
#' \code{surveyID}, \code{import_id}, \code{convert}, \code{label}, and
#' \code{breakout_sets}; passing those arguments errors because they are needed
#' for reliable dictionary-to-response-column mapping.
#' @details
#' Live calls require Qualtrics credentials configured for \code{qualtRics}
#' because response data are downloaded from the Qualtrics API. \code{qualtdict}
#' owns the \code{fetch_survey()} settings needed for reliable
#' Variable-Dictionary-to-response-column matching:
#' \code{import_id = TRUE}, \code{label = FALSE}, \code{convert = FALSE}, and
#' \code{breakout_sets = TRUE}. User-supplied passthrough arguments cannot
#' override those settings.
#'
#' By default, Labelled Survey Data includes variables with Validation Findings.
#' Use \code{exclude_findings} when you want to explicitly remove them after
#' download.
#' Because \code{quiet} follows \code{...}, supply it by name.
#'
#' @return
#' Labelled Survey Data: a data frame whose Export Variables are renamed to
#' \code{variable_name} and annotated with labels from the Variable Dictionary.
#'
#' @export
#' @examples
#' if (interactive()) {
#'   survey_id <- "SV_XXXXXXXXXXXXXXXX"
#'
#'   # Generate a dictionary
#'   mydict <- dict_generate(survey_id, variable_name = "question_name")
#'   survey_dat <- get_survey_data(mydict,
#'     unanswer_recode = -77,
#'     unanswer_recode_multi = 0
#'   )
#' }
get_survey_data <- function(dict,
                            extra_columns = c(
                              "externalDataReference", "startDate", "endDate"
                            ),
                            exclude_findings = c("none", "validation"),
                            ...,
                            quiet = TRUE) {
  checkarg_isqualtdict(dict)
  extra_columns_user_supplied <- !missing(extra_columns)
  checkarg_ischaracter(extra_columns, null_okay = TRUE)
  exclude_findings <- match.arg(exclude_findings)
  checkarg_isboolean(quiet)

  args <- list(...)
  args <- prepare_fetch_survey_args(args, dict)

  survey <- do.call(fetch_survey2, args)

  # Not sure why underscore is appended sometimes
  # when include_questions is specified
  colnames(survey) <- str_remove(colnames(survey), "_$")

  filtered_dict <- exclude_dict_findings(
    dict = dict,
    exclude_findings = exclude_findings,
    quiet = quiet
  )
  labelled_export_findings <- missing_response_column_findings(
    filtered_dict,
    survey
  )

  dat_recoded <- survey_recode(filtered_dict,
    dat = survey,
    extra_columns = extra_columns,
    extra_columns_user_supplied = extra_columns_user_supplied,
    unanswer_recode = args$unanswer_recode,
    unanswer_recode_multi = args$unanswer_recode_multi
  )

  attr(dat_recoded, "dict") <- filtered_dict
  attr(dat_recoded, "labelled_export_findings") <- labelled_export_findings
  dat_recoded
}
