#' Create Labelled Survey Data
#'
#' Download Qualtrics responses through \code{qualtRics} and apply a Variable
#' Dictionary generated by \code{\link[qualtdict]{dict_generate}}. Export
#' Variables are matched by \code{response_column_id}, renamed to
#' \code{variable_name}, and labelled with question, item, level, and label
#' metadata using \code{sjlabelled}.
#'
#' @param dict A Variable Dictionary returned by
#' \code{\link[qualtdict]{dict_generate}}.
#' @param extra_columns A character vector of raw response columns to retain in
#' the Labelled Survey Data in addition to Export Variables. Defaults to
#' \code{c("externalDataReference", "startDate", "endDate")}. Missing
#' user-specified columns error; missing default columns warn and are skipped.
#' Use \code{NULL} to retain no extra columns.
#' @param exclude_findings Which findings to exclude after survey download.
#' \code{"none"} keeps all downloaded variables represented in the Variable
#' Dictionary. \code{"validation"} excludes rows with Validation Findings,
#' \code{"unsupported"} excludes rows with Unsupported Structure Findings, and
#' \code{"all"} excludes both.
#' @param ... Other arguments passed to
#' \code{\link[qualtRics]{fetch_survey}}. Filtering arguments such as
#' \code{include_questions} may be passed through. qualtdict owns
#' \code{surveyID}, \code{import_id}, \code{convert}, \code{label}, and
#' \code{breakout_sets}; passing those arguments errors because they are needed
#' for reliable dictionary-to-response-column mapping.
#' @details
#' Live calls require Qualtrics credentials configured for \code{qualtRics}
#' because response data are downloaded from the Qualtrics API. \code{qualtdict}
#' owns the \code{fetch_survey()} settings needed for reliable
#' Variable-Dictionary-to-response-column matching:
#' \code{import_id = TRUE}, \code{label = FALSE}, \code{convert = FALSE}, and
#' \code{breakout_sets = TRUE}. User-supplied passthrough arguments cannot
#' override those settings.
#'
#' By default, Labelled Survey Data includes variables with Validation Findings
#' or Unsupported Structure Findings. Use \code{exclude_findings} when you want
#' to explicitly remove them after download.
#'
#' @return
#' Labelled Survey Data: a data frame whose Export Variables are renamed to
#' \code{variable_name} and annotated with labels from the Variable Dictionary.
#'
#' @export
#' @examples
#' \dontrun{
#' survey_id <- "SV_XXXXXXXXXXXXXXXX"
#'
#' # Generate a dictionary
#' mydict <- dict_generate(survey_id, variable_name = "question_name")
#' survey_dat <- get_survey_data(mydict,
#'   unanswer_recode = -77,
#'   unanswer_recode_multi = 0
#' )
#' }
get_survey_data <- function(dict,
                            extra_columns = c(
                              "externalDataReference", "startDate", "endDate"
                            ),
                            exclude_findings = c(
                              "none", "validation", "unsupported", "all"
                            ),
                            ...) {
  checkarg_isqualtdict(dict)
  extra_columns_user_supplied <- !missing(extra_columns)
  checkarg_ischaracter(extra_columns, null_okay = TRUE)
  exclude_findings <- match.arg(exclude_findings)

  args <- list(...)
  args <- prepare_fetch_survey_args(args, dict)

  survey <- do.call(fetch_survey2, args)

  # Not sure why underscore is appended sometimes
  # when include_questions is specified
  colnames(survey) <- str_remove(colnames(survey), "_$")

  filtered_dict <- exclude_dict_findings(
    dict = dict,
    exclude_findings = exclude_findings
  )

  dat_recoded <- survey_recode(filtered_dict,
    dat = survey,
    extra_columns = extra_columns,
    extra_columns_user_supplied = extra_columns_user_supplied,
    unanswer_recode = args$unanswer_recode,
    unanswer_recode_multi = args$unanswer_recode_multi
  )

  attr(dat_recoded, "dict") <- filtered_dict
  dat_recoded
}

default_extra_columns <- function() {
  c("externalDataReference", "startDate", "endDate")
}

owned_fetch_survey_args <- function() {
  c(
    "surveyID",
    "import_id",
    "importId",
    "convert",
    "label",
    "breakout_sets",
    "breakoutSets",
    "include_qids"
  )
}

prepare_fetch_survey_args <- function(args, dict) {
  blocked_args <- intersect(names(args), owned_fetch_survey_args())
  if (length(blocked_args) > 0) {
    rlang::abort(c(
      "These `fetch_survey()` arguments are owned by qualtdict.",
      i = paste(
        "Remove:",
        paste(sprintf("`%s`", blocked_args), collapse = ", ")
      )
    ))
  }

  args$force_request <- TRUE
  args$surveyID <- attr(dict, "surveyID")
  args$import_id <- TRUE
  args$convert <- FALSE
  args$label <- FALSE
  args$breakout_sets <- TRUE
  args
}

exclude_dict_findings <- function(dict,
                                  exclude_findings = c(
                                    "none", "validation", "unsupported", "all"
                                  )) {
  exclude_findings <- match.arg(exclude_findings)
  if (exclude_findings == "none") {
    return(dict)
  }

  excluded_response_column_ids <- character()
  excluded_qids <- character()

  if (exclude_findings %in% c("validation", "all")) {
    validation_findings <- dict_validate(dict)$validation_findings
    excluded_response_column_ids <- c(
      excluded_response_column_ids,
      validation_findings$response_column_id
    )
  }

  if (exclude_findings %in% c("unsupported", "all")) {
    unsupported_findings <- unsupported_structure_findings(dict)
    if ("response_column_id" %in% names(unsupported_findings)) {
      excluded_response_column_ids <- c(
        excluded_response_column_ids,
        unsupported_findings$response_column_id
      )
    }
    if ("qid" %in% names(unsupported_findings)) {
      excluded_qids <- c(excluded_qids, unsupported_findings$qid)
    }
  }

  excluded_response_column_ids <- unique(
    excluded_response_column_ids[!is.na(excluded_response_column_ids)]
  )
  excluded_qids <- unique(excluded_qids[!is.na(excluded_qids)])

  exclude_rows <- dict_response_column_id(dict) %in%
    excluded_response_column_ids
  if ("qid" %in% names(dict)) {
    exclude_rows <- exclude_rows | dict$qid %in% excluded_qids
  }

  copy_qualtdict_attrs(dict[!exclude_rows, ], dict)
}

copy_qualtdict_attrs <- function(dict, source) {
  attr(dict, "class") <- attr(source, "class")
  attr(dict, "surveyID") <- attr(source, "surveyID", exact = TRUE)
  attr(dict, "survey_name") <- attr(source, "survey_name", exact = TRUE)
  attr(dict, "unsupported_structure_findings") <-
    filter_unsupported_findings(
      unsupported_structure_findings(source),
      dict
    )
  attr(dict, "variable_name_findings") <-
    filter_variable_findings(
      attr(source, "variable_name_findings", exact = TRUE),
      dict
    )
  dict
}

filter_unsupported_findings <- function(findings, dict) {
  if (is.null(findings) || nrow(findings) == 0) {
    return(empty_unsupported_structure_findings())
  }

  keep <- rep(FALSE, nrow(findings))
  has_identity <- FALSE
  if ("response_column_id" %in% names(findings)) {
    keep <- keep |
      findings$response_column_id %in% unique(dict_response_column_id(dict))
    has_identity <- TRUE
  }
  if ("qid" %in% names(findings) && "qid" %in% names(dict)) {
    keep <- keep | findings$qid %in% unique(dict$qid)
    has_identity <- TRUE
  }
  if (!has_identity) {
    keep <- rep(TRUE, nrow(findings))
  }

  findings[keep, ]
}

filter_variable_findings <- function(findings, dict) {
  if (is.null(findings) || nrow(findings) == 0) {
    return(empty_variable_name_findings())
  }

  findings[
    findings$response_column_id %in% unique(dict_response_column_id(dict)),
  ]
}

resolve_extra_columns <- function(dat,
                                  extra_columns,
                                  extra_columns_user_supplied) {
  if (is.null(extra_columns)) {
    return(character())
  }

  missing_extra_columns <- setdiff(extra_columns, colnames(dat))
  if (length(missing_extra_columns) > 0) {
    missing_message <- paste(
      sprintf("`%s`", missing_extra_columns),
      collapse = ", "
    )
    if (extra_columns_user_supplied) {
      rlang::abort(c(
        "Missing user-specified `extra_columns` in downloaded survey data.",
        i = paste("Missing:", missing_message)
      ))
    }

    warning(
      paste(
        "Missing default `extra_columns` in downloaded survey data:",
        missing_message
      ),
      call. = FALSE
    )
  }

  extra_columns[extra_columns %in% colnames(dat)]
}

#' Add labels to survey
#' @keywords internal
#' @noRd
survey_recode <- function(dict,
                          dat,
                          extra_columns = default_extra_columns(),
                          extra_columns_user_supplied = FALSE,
                          unanswer_recode,
                          unanswer_recode_multi) {
  response_column_id <- dict_response_column_id(dict)
  in_dat <- response_column_id %in% colnames(dat)
  dict <- dict[in_dat, ]
  response_column_id <- response_column_id[in_dat]
  unique_response_column_ids <- unique(response_column_id)
  unique_varnames <- unique(dict_variable_name(dict))

  extra_columns <- resolve_extra_columns(
    dat = dat,
    extra_columns = extra_columns,
    extra_columns_user_supplied = extra_columns_user_supplied
  )
  extra_columns <- setdiff(extra_columns, unique_response_column_ids)
  dat_cols <- unique(c(extra_columns, unique_response_column_ids))

  if (length(unique_response_column_ids) == 0) {
    return(dat[dat_cols])
  }

  varnames <- setNames(unique_response_column_ids, unique_varnames)
  dat <- rename(dat[dat_cols], !!!varnames)

  # level = unique to preserve ordering
  split_dict <- split(
    dict,
    factor(response_column_id, levels = unique_response_column_ids)
  )
  dat_vars <- map2_df(
    dat[unique_varnames], split_dict,
    ~ survey_var_recode(.x, .y,
      unanswer_recode = unanswer_recode,
      unanswer_recode_multi = unanswer_recode_multi
    )
  )

  bind_cols(dat[extra_columns], dat_vars)
}

dict_response_column_id <- function(dict) {
  if ("response_column_id" %in% names(dict)) {
    return(dict[["response_column_id"]])
  }

  dict[["qid"]]
}

dict_variable_name <- function(dict) {
  if ("variable_name" %in% names(dict)) {
    return(dict[["variable_name"]])
  }

  dict[["name"]]
}

#' Add labels to each variable in survey (`sjlabelled` uses `haven`)
#' @importFrom sjlabelled set_label set_labels
#' @importFrom haven read_xpt
#' @keywords internal
#' @noRd
survey_var_recode <- function(var,
                              var_dict,
                              unanswer_recode,
                              unanswer_recode_multi) {
  # Multiple rows for a question, only first one chosen
  type <- var_dict[["type"]][1]
  content_type <- var_dict[["content_type"]][[1]]
  levels <- var_dict[["level"]]
  labels <- var_dict[["label"]]
  is_text_var <- type == "TE" || any(grepl("_TEXT", levels))

  if (!is_text_var && !is.na(content_type) && content_type == "Number") {
    # Check for content_type numeric,
    # vector with numbers such as "06" passes validation on Qualtrics but
    # will be character when read by readr

    var <- as.numeric(var)
  }

  if (is_text_var) {
    levels <- NA

  } else if (nrow(var_dict) == 1) {
    # Single row means allowing for multiple answer
    if (!is.null(unanswer_recode_multi)) {
      levels <- c(levels, unanswer_recode_multi)
      labels <- c(labels, paste("Not", labels))
    }
  } else if (nrow(var_dict) > 1) {
    # If multiple rows it's ordinal
    labels <- grep("TEXT", labels, invert = TRUE, value = TRUE)
    levels <- grep("TEXT", levels, invert = TRUE, value = TRUE)
    if (!is.null(unanswer_recode)) {
      levels <- c(levels, unanswer_recode)
      labels <- c(labels, "Seen but not answered")
    }
  }

  # TE variables dont have levels or labels
  if (any(!is.na(levels))) {
    var <- set_labels(var, labels = setNames(levels, labels))
  } else {
    text_label <- unique(paste_narm(var_dict[["question"]], var_dict[["item"]]))
    var <- set_label(var, label = text_label)
  }


  return(var)
}
